# Go linting configuration
# Run with: golangci-lint run

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/multifrost/golang

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
