"""
FILE: python/src/multifrost/__init__.py
PURPOSE: Publish the canonical v5 Python surface from the package root.
OWNS: Top-level imports for caller helpers, service runners, protocol primitives, and error types.
EXPORTS: connect, spawn, Connection, Handle, HandleSync, ServiceProcess, ServiceWorker, ServiceContext, run_service, run_service_sync, protocol constants, frame helpers, and v5 errors.
DOCS: docs/spec.md; agent_chat/python_v5_api_surface_2026-03-25.md
"""

from .connection import Connection, ConnectOptions, Handle, connect
from .errors import (
    BootstrapError,
    ErrorOrigin,
    MalformedFrameError,
    MultifrostError,
    RegistrationError,
    RemoteCallError,
    RouterError,
    TransportError,
    error_from_body,
)
from .frame import (
    FrameParts,
    decode_body,
    decode_envelope,
    decode_frame,
    decode_msgpack,
    encode_body,
    encode_envelope,
    encode_frame,
    encode_msgpack,
)
from .process import ServiceProcess, SpawnOptions, spawn
from .protocol import (
    DEFAULT_ROUTER_PORT,
    INT64_MAX,
    INT64_MIN,
    PROTOCOL_KEY,
    PROTOCOL_VERSION,
    ROUTER_BIN_ENV,
    ROUTER_LOCK_PATH_SUFFIX,
    ROUTER_LOG_PATH_SUFFIX,
    ROUTER_PEER_ID,
    ROUTER_PORT_ENV,
    CallBody,
    Envelope,
    ErrorBody,
    PeerClass,
    QueryBody,
    QueryExistsResponseBody,
    QueryGetResponseBody,
    RegisterAckBody,
    RegisterBody,
    ResponseBody,
    build_call_envelope,
    build_disconnect_envelope,
    build_error_envelope,
    build_heartbeat_envelope,
    build_query_envelope,
    build_register_envelope,
    build_response_envelope,
    call,
    caller,
    disconnect,
    error,
    heartbeat,
    new_msg_id,
    now_ts,
    query,
    query_peer_exists,
    query_peer_get,
    register,
    register_ack,
    response,
    service,
)
from .router_bootstrap import RouterBootstrapConfig, bootstrap_router
from .service import ServiceContext, ServiceWorker, run_service, run_service_sync
from .sync import HandleSync

__version__ = "5.0.0"

__all__ = [
    "__version__",
    "connect",
    "spawn",
    "Connection",
    "Handle",
    "HandleSync",
    "ServiceProcess",
    "ServiceWorker",
    "ServiceContext",
    "run_service",
    "run_service_sync",
    "ConnectOptions",
    "SpawnOptions",
    "RouterBootstrapConfig",
    "bootstrap_router",
    "PROTOCOL_KEY",
    "PROTOCOL_VERSION",
    "DEFAULT_ROUTER_PORT",
    "ROUTER_BIN_ENV",
    "ROUTER_LOG_PATH_SUFFIX",
    "ROUTER_LOCK_PATH_SUFFIX",
    "ROUTER_PEER_ID",
    "ROUTER_PORT_ENV",
    "service",
    "caller",
    "register",
    "register_ack",
    "query",
    "query_peer_exists",
    "query_peer_get",
    "call",
    "response",
    "error",
    "heartbeat",
    "disconnect",
    "INT64_MIN",
    "INT64_MAX",
    "PeerClass",
    "Envelope",
    "RegisterBody",
    "RegisterAckBody",
    "QueryBody",
    "QueryExistsResponseBody",
    "QueryGetResponseBody",
    "CallBody",
    "ResponseBody",
    "ErrorBody",
    "FrameParts",
    "encode_msgpack",
    "decode_msgpack",
    "encode_envelope",
    "decode_envelope",
    "encode_body",
    "decode_body",
    "encode_frame",
    "decode_frame",
    "MultifrostError",
    "TransportError",
    "MalformedFrameError",
    "BootstrapError",
    "RegistrationError",
    "RouterError",
    "RemoteCallError",
    "ErrorOrigin",
    "error_from_body",
    "now_ts",
    "new_msg_id",
    "build_register_envelope",
    "build_query_envelope",
    "build_call_envelope",
    "build_response_envelope",
    "build_error_envelope",
    "build_disconnect_envelope",
    "build_heartbeat_envelope",
]
